{
 "title": "Twitch ES",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_name",
    "label": "User Name",
    "query": "{\"find\": \"terms\", \"field\": \"user_name\", \"size\": 1000}"
   },
   {
    "name": "game_name",
    "label": "Game Name",
    "query": "{\"find\": \"terms\", \"field\": \"game_name\", \"size\": 1000}"
   }
  ]
 },
 "panels": [
  {
   "title": "Monitored Streamers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "monitored streamer",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "user_id", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Viewer Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "viewer_count",
       "id": "1",
       "settings": {
        "percents": [
         "25",
         "50",
         "75",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Viewers",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "viewer_count",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(game_name:$game_name) AND (user_name: $user_name)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "follower_count",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(game_name:$game_name) AND (user_name: $user_name)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Games",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "game_name",
       "id": "3",
       "settings": { "min_doc_count": "10", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "viewer_count",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(game_name:$game_name) AND (user_name: $user_name)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Derivative",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_name",
       "id": "3",
       "settings": { "min_doc_count": "10", "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "viewer_count",
       "hide": true,
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "(game_name:$game_name) AND (user_name: $user_name)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}